In [1]:
import pandas as pd
import numpy as np

In [2]:
critics = pd.read_csv('dataset/f_critics.csv', index_col=0)
audience = pd.read_csv('dataset/f_audience.csv', index_col=0)
reviews_aa = pd.read_csv('dataset/audience_fresh.csv', index_col=0)
reviews_ac = pd.read_csv('dataset/audience_rotten.csv', index_col=0)
reviews_ca = pd.read_csv('dataset/critics_rotten.csv', index_col=0)
reviews_cc = pd.read_csv('dataset/critics_fresh.csv', index_col=0)

In [3]:
reviews_aa.dropna(inplace=True)
reviews_ac.dropna(inplace=True)
reviews_ca.dropna(inplace=True)
reviews_cc.dropna(inplace=True)

In [4]:
audience_reviews = pd.concat([reviews_aa, reviews_ac])
critics_reviews = pd.concat([reviews_ca, reviews_cc])

In [5]:
movie_ids = pd.read_csv('dataset/movie_ids.csv', index_col=0).set_index('id')

In [6]:
audience_reviews = audience_reviews.merge(movie_ids, left_index=True, right_index=True).set_index('rotten_tomatoes_link')
audience_reviews

,review_content,is_fresh
rotten_tomatoes_link,,
m/baps,Amazing favorite movie,True
m/baps,Nothing wrong with gaining beyond what you ask...,True
m/baps,This film is one of my top five favorite films...,True
m/baps,Favorite movie best movie to watch and laugh w...,True
m/baps,"LOL, the funniest 01 hour: and 31 minutes ever...",True
...,...,...
m/knock_down_the_house,Charting intriguing characters who tries to br...,False
m/knock_down_the_house,"Just propaganda, it wasn't a real movie or doc...",False
m/knock_down_the_house,"OMG 100% from critics, what a bunch of BS!",False
m/knock_down_the_house,Enough already with this lady. Running Amazon ...,False
m/knock_down_the_house,The timely nature of this political documentar...,False

In [7]:
critics_reviews = critics_reviews.merge(movie_ids, left_index=True, right_index=True).set_index('rotten_tomatoes_link')
critics_reviews

,review_content,is_fresh
rotten_tomatoes_link,,
m/baps,"Halle Berry gives this her all, but the script...",False
m/baps,A string of hugely unfunny shenanigans ensue.,False
m/baps,"Formulaic and distastefully fake, Townsend's m...",False
m/baps,"You can see how the black, modern-day Pygmalio...",False
m/baps,The story offers nothing original.,False
...,...,...
m/knock_down_the_house,"Lears gains great drama out of all the women, ...",True
m/knock_down_the_house,It's thrilling to watch a film that makes chan...,True
m/knock_down_the_house,It is inspiring to simply watch these ordinary...,True
m/knock_down_the_house,Outstanding docu about underdog Congressional ...,True
m/knock_down_the_house,As 'Knock Down the House' argues so compelling...,True

In [8]:
audience_reviews.review_content = audience_reviews.review_content.str.lower()
audience_reviews

,review_content,is_fresh
rotten_tomatoes_link,,
m/baps,amazing favorite movie,True
m/baps,nothing wrong with gaining beyond what you ask...,True
m/baps,this film is one of my top five favorite films...,True
m/baps,favorite movie best movie to watch and laugh w...,True
m/baps,"lol, the funniest 01 hour: and 31 minutes ever...",True
...,...,...
m/knock_down_the_house,charting intriguing characters who tries to br...,False
m/knock_down_the_house,"just propaganda, it wasn't a real movie or doc...",False
m/knock_down_the_house,"omg 100% from critics, what a bunch of bs!",False
m/knock_down_the_house,enough already with this lady. running amazon ...,False
m/knock_down_the_house,the timely nature of this political documentar...,False

In [9]:
critics_reviews.review_content = critics_reviews.review_content.str.lower()
critics_reviews

,review_content,is_fresh
rotten_tomatoes_link,,
m/baps,"halle berry gives this her all, but the script...",False
m/baps,a string of hugely unfunny shenanigans ensue.,False
m/baps,"formulaic and distastefully fake, townsend's m...",False
m/baps,"you can see how the black, modern-day pygmalio...",False
m/baps,the story offers nothing original.,False
...,...,...
m/knock_down_the_house,"lears gains great drama out of all the women, ...",True
m/knock_down_the_house,it's thrilling to watch a film that makes chan...,True
m/knock_down_the_house,it is inspiring to simply watch these ordinary...,True
m/knock_down_the_house,outstanding docu about underdog congressional ...,True
m/knock_down_the_house,as 'knock down the house' argues so compelling...,True

In [10]:
critics_reviews = critics_reviews.drop(columns=['is_fresh'])
critics_reviews

                                                           review_content
rotten_tomatoes_link
m/baps                  halle berry gives this her all, but the script...
m/baps                      a string of hugely unfunny shenanigans ensue.
m/baps                  formulaic and distastefully fake, townsend's m...
m/baps                  you can see how the black, modern-day pygmalio...
m/baps                                 the story offers nothing original.
...                                                                   ...
m/knock_down_the_house  lears gains great drama out of all the women, ...
m/knock_down_the_house  it's thrilling to watch a film that makes chan...
m/knock_down_the_house  it is inspiring to simply watch these ordinary...
m/knock_down_the_house  outstanding docu about underdog congressional ...
m/knock_down_the_house  as 'knock down the house' argues so compelling...

[20867 rows x 1 columns]

In [11]:
audience_reviews = audience_reviews.drop(columns=['is_fresh'])
audience_reviews

                                                           review_content
rotten_tomatoes_link
m/baps                                             amazing favorite movie
m/baps                  nothing wrong with gaining beyond what you ask...
m/baps                  this film is one of my top five favorite films...
m/baps                  favorite movie best movie to watch and laugh w...
m/baps                  lol, the funniest 01 hour: and 31 minutes ever...
...                                                                   ...
m/knock_down_the_house  charting intriguing characters who tries to br...
m/knock_down_the_house  just propaganda, it wasn't a real movie or doc...
m/knock_down_the_house         omg 100% from critics, what a bunch of bs!
m/knock_down_the_house  enough already with this lady. running amazon ...
m/knock_down_the_house  the timely nature of this political documentar...

[21103 rows x 1 columns]

In [12]:
critics_reviews.to_csv('dataset/critics_reviews_clean_v2.csv')
audience_reviews.to_csv('dataset/audience_reviews_clean_v2.csv')